- name: Commit and Push Data
        run: |
          git config --global user.name 'Syndicate-Agent'
          git config --global user.email 'agent@xcott.com'
          git add latest_predictions.csv
          git commit -m "New Prediction Feed Delivered" || exit 0
          git push
